<a href="https://colab.research.google.com/github/kambleutkarsha603-rgb/ML124/blob/main/utkarsha.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [6]:
import numpy as np
np .array(my_list)

array([1, 2, 3])

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np .array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np .zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,3,))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(9,10,3)

array([ 9. ,  9.5, 10. ])

In [18]:
np.linspace(0,10,50
            )

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(2)

array([0.92952069, 0.52619606])

In [21]:
np.random.rand(5,5)

array([[0.93450237, 0.55759876, 0.67892791, 0.10615912, 0.54220004],
       [0.34579141, 0.78681593, 0.35265087, 0.46328604, 0.38021151],
       [0.54610197, 0.01880858, 0.07667193, 0.37128753, 0.71481222],
       [0.67456503, 0.4334108 , 0.4828261 , 0.38478212, 0.09549828],
       [0.26610385, 0.52468264, 0.90675723, 0.18255596, 0.78766669]])

In [22]:
np.random.randn(2)

array([ 1.40821557, -0.06762043])

In [23]:
np.random.randn(5,5)

array([[ 1.81916527, -1.30439679,  1.54596072,  0.67510858, -1.51816426],
       [-0.15108412, -1.07201587,  1.3828823 , -1.0501477 , -1.9267801 ],
       [-1.70569465, -1.11548634, -0.04772111, -0.9415807 , -0.4894619 ],
       [ 0.34498681,  1.2780926 ,  0.03342546,  1.5376777 ,  0.19487143],
       [ 0.83725356,  0.39961769, -1.19528031,  0.40826424, -1.05348882]])

In [25]:
np.random.randint(1,100)

92

In [26]:
np.random.randint(1,100,10)

array([64,  2,  3, 80, 56, 65, 63, 63, 16, 88])

In [34]:
arr =np.arange(25)
ranarr =np.random.randint(0,50,10)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
ranarr

array([ 4, 32, 27, 43, 11,  6, 47, 31,  6,  9])